# Generated by Django 2.1.2 on 2018-11-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingListIndi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_person', models.CharField(max_length=200)),
                ('industry_name', models.CharField(max_length=100)),
                ('date_visit', models.DateField()),
                ('slots_present', models.IntegerField()),
                ('visting_members', models.IntegerField()),
                ('street_name', models.CharField(max_length=150)),
                ('city_name', models.CharField(max_length=100)),
                ('pin_code', models.IntegerField()),
                ('code', models.CharField(max_length=10)),
                ('visited', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='BookingListOrga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_person', models.CharField(max_length=200)),
                ('organisation_name', models.CharField(max_length=200)),
                ('industry_name', models.CharField(max_length=100)),
                ('date_visit', models.DateField()),
                ('slots_present', models.IntegerField()),
                ('street_name', models.CharField(max_length=150)),
                ('city_name', models.CharField(max_length=100)),
                ('pin_code', models.IntegerField()),
                ('code', models.CharField(max_length=10)),
                ('visited', models.BooleanField()),
            ],
        ),
    ]
