# Generated by Django 2.1.2 on 2018-11-02 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinglistindi',
            name='date_visit',
        ),
        migrations.RemoveField(
            model_name='bookinglistorga',
            name='date_visit',
        ),
    ]
