# Generated by Django 2.1.2 on 2018-11-03 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20181103_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinglistindi',
            name='date_visit',
            field=models.DateField(default=datetime.datetime(2018, 11, 3, 15, 56, 23, 635116)),
        ),
        migrations.AddField(
            model_name='bookinglistorga',
            name='date_visit',
            field=models.DateField(default=datetime.datetime(2018, 11, 3, 15, 56, 23, 636241)),
        ),
    ]
