# Generated by Django 2.1.2 on 2018-11-03 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20181103_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinglistindi',
            name='date_visit',
            field=models.DateField(default=datetime.datetime(2018, 11, 3, 18, 22, 4, 713047)),
        ),
        migrations.AlterField(
            model_name='bookinglistorga',
            name='date_visit',
            field=models.DateField(default=datetime.datetime(2018, 11, 3, 18, 22, 4, 714036)),
        ),
    ]
