# Generated by Django 2.1.2 on 2018-11-12 07:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20181103_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinglistorga',
            old_name='slots_present',
            new_name='visiting_members',
        ),
        migrations.RemoveField(
            model_name='bookinglistindi',
            name='slots_present',
        ),
        migrations.AddField(
            model_name='bookinglistindi',
            name='slot_time',
            field=models.CharField(choices=[('1', '9:30'), ('2', '11:30'), ('3', '14:30')], default='9:30', max_length=10),
        ),
        migrations.AddField(
            model_name='bookinglistorga',
            name='slot_time',
            field=models.CharField(choices=[('1', '9:30'), ('2', '11:30'), ('3', '14:30')], default='9:30', max_length=10),
        ),
        migrations.AlterField(
            model_name='bookinglistindi',
            name='date_visit',
            field=models.DateField(default=datetime.datetime(2018, 11, 12, 12, 56, 7, 535757)),
        ),
        migrations.AlterField(
            model_name='bookinglistorga',
            name='date_visit',
            field=models.DateField(default=datetime.datetime(2018, 11, 12, 12, 56, 7, 536703)),
        ),
    ]
