# Generated by Django 2.1.3 on 2018-12-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0002_userprofileinfo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='image',
            field=models.ImageField(default='media/default.jpg', null=True, upload_to='profile_pics'),
        ),
    ]
