# Generated by Django 2.1.2 on 2018-12-12 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searchBarApp', '0003_addtovisitlater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtovisitlater',
            name='industry_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addtovisitlater',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
