# Generated by Django 2.1.2 on 2018-12-12 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searchBarApp', '0004_auto_20181212_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtovisitlater',
            name='industry_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='searchBarApp.industry'),
        ),
    ]
