# Generated by Django 2.1.2 on 2018-11-18 09:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingListIndi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_person', models.CharField(max_length=200)),
                ('industry_name', models.CharField(max_length=100)),
                ('date_visit', models.DateField(default=django.utils.timezone.now)),
                ('slot_time', models.CharField(choices=[('1', '9:30'), ('2', '11:30'), ('3', '14:30')], default='9:30', max_length=10)),
                ('visiting_members', models.IntegerField(default=0)),
                ('total_available', models.IntegerField(default=20)),
                ('total_taken', models.IntegerField(default=0)),
                ('street_name', models.CharField(max_length=150)),
                ('city_name', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=20)),
                ('visited', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BookingListOrga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_person', models.CharField(max_length=200)),
                ('organisation_name', models.CharField(max_length=200)),
                ('industry_name', models.CharField(max_length=100)),
                ('date_visit', models.DateField(default=django.utils.timezone.now)),
                ('slot_time', models.CharField(choices=[('1', '9:30'), ('2', '11:30'), ('3', '14:30')], default='9:30', max_length=10)),
                ('visiting_members', models.IntegerField(default=0)),
                ('total_available', models.IntegerField(default=20)),
                ('total_taken', models.IntegerField(default=0)),
                ('street_name', models.CharField(max_length=150)),
                ('city_name', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=20)),
                ('visited', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('slot', models.CharField(max_length=10)),
                ('ticks', models.IntegerField(default=20)),
            ],
        ),
    ]
