# Generated by Django 2.1.3 on 2018-11-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20181118_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinglistindi',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='bookinglistorga',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
