# Generated by Django 2.1.3 on 2018-11-19 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20181118_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinglistindi',
            name='user',
        ),
        migrations.RemoveField(
            model_name='bookinglistorga',
            name='user',
        ),
    ]
