# Generated by Django 2.1.3 on 2018-11-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchBarApp', '0001_initial'),
        ('booking', '0005_auto_20181121_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinglistindi',
            name='user1_multi',
            field=models.ManyToManyField(null=True, to='searchBarApp.industry'),
        ),
        migrations.AddField(
            model_name='bookinglistorga',
            name='user1_multi',
            field=models.ManyToManyField(null=True, to='searchBarApp.industry'),
        ),
    ]
