# Generated by Django 2.1.3 on 2018-11-24 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20181124_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinglistindi',
            name='user1_multi',
        ),
        migrations.RemoveField(
            model_name='bookinglistorga',
            name='user1_multi',
        ),
    ]
