# Generated by Django 2.1.3 on 2018-12-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20181125_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinglistindi',
            name='left_days_bool',
            field=models.BooleanField(default=True),
        ),
    ]
