# Generated by Django 2.1.3 on 2018-11-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Organisation', models.CharField(blank=True, max_length=50)),
                ('date_visit', models.DateField()),
            ],
        ),
    ]
