# Generated by Django 2.1.3 on 2018-12-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practise', '0002_info_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('services', models.CharField(choices=[('Very Good', 'Very good'), ('Good', 'good'), ('Bad', 'Bad')], max_length=15)),
                ('Guide', models.CharField(choices=[('Very Good', 'Very good'), ('Good', 'good'), ('Bad', 'Bad')], max_length=15)),
            ],
        ),
    ]
